version: '3.8'

services:
  qixin-mcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: qixin-mcp-server
    environment:
      - MCP_SSE=${MCP_SSE:-false}
      - MCP_STREAMABLE_HTTP=${MCP_STREAMABLE_HTTP:-false}
      - PORT=3000
      - QIXIN_APP_KEY=${QIXIN_APP_KEY}
      - QIXIN_SECRET_KEY=${QIXIN_SECRET_KEY}
      - QIXIN_BASE_URL=${QIXIN_BASE_URL:-https://api.qixin.com/APIService}
      - QIXIN_TIMEOUT=${QIXIN_TIMEOUT:-30000}
      - QIXIN_MAX_RETRIES=${QIXIN_MAX_RETRIES:-3}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s